### PR TITLE
Show error code actually in error message

### PR DESCRIPTION
**Pull request by robert-scheck**

### CODE REVIEW

**Comment by matidau** [comment]
Hi Robert,

Thanks for the PR. For testing purposes can you provide some additional info on your environment?

Distro and version
PHP version
Kopano Version
Mobile device (optional) 

Also as a first time contributor please state that this commit is:

> Released under the Affero GNU General Public License (AGPL) version 3.

Cheers,
Mat

**Comment by robert-scheck** [comment]
> Thanks for the PR. For testing purposes can you provide some additional info on your environment?

I'm not sure how this would be relevant for such a trivial change that exists in the same way already 10 code lines below.

> Also as a first time contributor please state that this commit is:

I'm _not_ a first time contributor to Z-Push, but one of the people who implicitly more or less caused in 2010 the switch to the current license. Alternatively, see [here](https://github.com/Z-Hub/Z-Push/blob/39f7e76ba90b5134346d31095b31b969047b0f6a/src/lib/utils/utils.php#L883) for a contribution from 2012.

**Comment by matidau** [comment]
> I'm not sure how this would be relevant for such a trivial change that exists in the same way already 10 code lines below.

I will still test it and this would be useful information for me. If you don't want to provide it, no problems it will still be reviewed. 

> I'm _not_ a first time contributor to Z-Push, but one of the people who implicitly more or less caused in 2010 the switch to the current license. Alternatively, see [here](https://github.com/Z-Hub/Z-Push/blob/39f7e76ba90b5134346d31095b31b969047b0f6a/src/lib/utils/utils.php#L883) for a contribution from 2012.

Sorry I should have said first time contributor through Github. 

I've had a look and I can't find a commit message from yourself where you have released the code under AGPLv3. Can provide a link to this or similar statement in relation to Z-Push?

**Comment by robert-scheck** [comment]
> I've had a look and I can't find a commit message from yourself where you have released the code under AGPLv3. Can provide a link to this or similar statement in relation to Z-Push?

I'm sorry to say that, but this separate license confirmation request feels quite strange; I suggest a [DCO](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin) to allow common `Signed-off-by:` for the future. My contribution is released under the license stated in the header of the file the contribution actually happened to.

**Comment by matidau** [comment]
> I'm sorry to say that, but this separate license confirmation request feels quite strange; I suggest a [DCO](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin) to allow common `Signed-off-by:` for the future. My contribution is released under the license stated in the header of the file the contribution actually happened to.

If you are willing to manage and maintain these for the project this may be a path forward, but should be discussed with other contributors first. I think it has greater overhead than the current approach. 

The message is as per Kopano's previous wiki
https://kb.kopano.io/display/ZP/Development+guidelines

Which is duplicated in the community project's wiki
https://github.com/Z-Hub/Z-Push/wiki/Development-Guidelines#commit-message

Asking for the message once instead of with each commit I feel is the right balance between explicitly declaring and not burdening contributors with too much additional paperwork.

I will close this off and not review it further. Feel free to explicitly release the code on this PR, or open another one in the future and release it there.

**Comment by matidau** [comment]
Commit not released under the AGPLv3

**Comment by robert-scheck** [comment]
> I will close this off and not review it further. Feel free to explicitly release the code on this PR, or open another one in the future and release it there.

I will not release this code under explicitly "AGPLv3" (SPDX: [AGPL-3.0-only](https://spdx.org/licenses/AGPL-3.0-only.html)), just under the terms and conditions of the current license of this project, because Z-Push is currently licensed as "AGPLv3 with exceptions" (no SPDX yet, I think), see the file [src/LICENSE line 664 and following](https://github.com/Z-Hub/Z-Push/blob/develop/src/LICENSE#L664) for details.

**Comment by matidau** [comment]
Would you be willing to release under the updated wording?

> Released under the GNU Affero General Public License (AGPL), version 3 and Trademark Additional Terms.

from [CONTRIBUTING](https://github.com/Z-Hub/Z-Push/blob/develop/CONTRIBUTING.md#releasing-contributions)

**Pull request closed without merging**
