### PR TITLE
Implement AS 16 Find command to fix e-mail search on iOS 16+

### PR DESCRIPTION
**Pull request by mschering**
What does this implement/fix? Explain your changes.
---------------------------------------------------
iOS 16 and up wrongfully sends a Find command when searching mail using Z-Push. I implemented the Find command so that searching works on iOS 16.

Does this close any currently open issues?
------------------------------------------
Fixes Error when searching mail on iphone #23

Any relevant logs, error output, etc?
-------------------------------------
No

Where has this been tested?
---------------------------
**Server (please complete the following information):**
 - OS: Linux
 - PHP Version: 8.2
 - Backend for: Group-Office
 - and Version: 6.8

**Smartphone (please complete the following information):**
 - Device: IPhone 13
 - OS: iOS 17.4
 - Mail App Apple mail

### CODE REVIEW

**Comment by liverpoolfc-fan** [comment]
PHP 8.2 changes, if needed, should not be in an AS16.1 ticket. You should open a seperate issue for that.

**Comment by matidau** [comment]
> PHP 8.2 changes, if needed, should not be in an AS16.1 ticket.

I agree with this, though I think some of it only relates to changes after AS16.1 has been made.

To muddy the waters I was also working on AS16.1 changes last year for Kopano based on grommunio-sync #59

**Comment by mschering** [comment]
I agree, I added those by mistake. I'll figure out how to remove those from here.

**Comment by mschering** [comment]
I've created a new branch for this pull request without that last commit and opened a new pull request:

https://github.com/Z-Hub/Z-Push/pull/60

I will close this one.

**Pull request closed without merging**
